name: Dotnet Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build for linux 64
      run: dotnet publish SusLang -c Release -r linux-x64 -p:PublishSingleFile=true -p:PublishAot=false --self-contained true
    - name: Build for windows (x86)
      run: dotnet publish SusLang -c Release -r win-x86 -p:PublishSingleFile=true -p:PublishAot=false --self-contained true
    - name: Upload linux build
      uses: actions/upload-artifact@v3
      with:
        name: Linux-x64
        path: SusLang/bin/Release/net7.0/linux-x64/publish
    - name: Upload windows build
      uses: actions/upload-artifact@v3
      with:
        name: Win-x86
        path: SusLang/bin/Release/net7.0/win-x86/publish
